matches:
  - trigger: ":upv"
    replace: Universitat Politècnica de València
    word: true
  - trigger: ":espanso"
    replace: Hi there!
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
