matches:
  - trigger: ":upv"
    replace: Universitat Politècnica de València
    word: true
  - trigger: ":vrain"
    replace: Valencian Research Institute for Artificial Intelligence
  - trigger: ":eur"
    replace: "€"
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
