[beets.files]
"modules/beets" = "~/.config/beets"

[inkscape.files]
"modules/inkscape" = "~/.config/inkscape"

[shell.files]
"modules/shell/bashrc.sh"         = "~/.bashrc"
"modules/shell/bashrc_default.sh" = "~/.bashrc_default"
"modules/shell/bash_aliases.sh"   = "~/.bash_aliases"
"modules/shell/inputrc"           = "~/.inputrc"

[shell_local.files]
"modules/shell/bash_local.sh" = "~/.bash_local"

[prompt.files]
"modules/shell/bash_prompt.sh" = "~/.bash_prompt"
"modules/shell/starship.toml"  = "~/.config/starship.toml"

[ssh.files]
"modules/ssh" = "~/.ssh"

[git.files]
"modules/git/gitconfig" = "~/.gitconfig"
"modules/git/gitignore" = "~/.gitignore"

[python.files]
"modules/python/pep8"     = "~/.config/pep8"
"modules/python/pylintrc" = "~/.pylintrc"

[node.files]
"modules/node/npmrc" = "~/.npmrc"

[nixos-home.files]
"modules/nixos-home/home.nix" = "~/.config/nixpkgs/home.nix"

[nix-home.files]
"modules/nix-home/home.nix" = "~/.config/nixpkgs/home.nix"

[espanso.files]
"modules/espanso" = { target = "~/.config/espanso", type = "symbolic" }
