[beets.files]
"config/beets" = "~/.config/beets"

[inkscape.files]
"config/inkscape" = "~/.config/inkscape"

[shell.files]
"shell/bashrc.sh"         = "~/.bashrc"
"shell/bashrc_default.sh" = "~/.bashrc_default"
"shell/bash_aliases.sh"   = "~/.bash_aliases"
"shell/inputrc"           = "~/.inputrc"

[shell_prompt.files]
"shell/bash_prompt.sh" = "~/.bash_prompt"
"shell/starship.toml"  = "~/.config/starship.toml"

[ssh.files]
ssh = "~/.ssh"

[git.files]
"git/gitconfig" = "~/.gitconfig"
"git/gitignore" = "~/.gitignore"

[python.files]
"config/pep8" = "~/.config/pep8"
pylintrc      = "~/.pylintrc"


[nix-home.files]
"nix/home.nix" = "~/.config/nixpkgs/home.nix"
