[beets.files]
"modules/beets" = "~/.config/beets"

[inkscape.files]
"modules/inkscape" = "~/.config/inkscape"

[shell.files]
"modules/shell/inputrc"                 = "~/.inputrc"
"modules/shell/bashrc.sh"               = "~/.bashrc"
"modules/shell/bashrc_default.sh"       = "~/.config/shell/bashrc_default.sh"
"modules/shell/bash_profile.sh"         = "~/.bash_profile"
"modules/shell/bash_profile_default.sh" = "~/.config/shell/bash_profile_default.sh"
"modules/shell/bash_aliases.sh"         = "~/.config/shell/bash_aliases.sh"

[shell_local.files]
"modules/shell/bash_local.sh" = "~/.config/shell/bash_local.sh"

[prompt.files]
"modules/shell/bash_prompt.sh" = "~/.config/shell/bash_prompt.sh"
"modules/shell/starship.toml"  = "~/.config/starship.toml"

[ssh.files]
"modules/ssh" = "~/.ssh"

[git.files]
"modules/git/gitconfig" = "~/.gitconfig"
"modules/git/gitignore" = "~/.gitignore"

[python.files]
"modules/python/pep8"        = "~/.config/pep8"
"modules/python/pylintrc"    = "~/.pylintrc"
"modules/python/poetry.toml" = "~/.config/pypoetry/config.toml"

[node.files]
"modules/node/npmrc" = "~/.npmrc"

[nixos-home.files]
"modules/nixos-home/home.nix" = "~/.config/home-manager/home.nix"

[nix-home.files]
"modules/nix-home/home.nix"          = { target = "~/.config/home-manager/home.nix", type = "symbolic" }
"modules/nix-home/nixhomeprofile.sh" = "~/.config/home-manager/nixhomeprofile.sh"
